### ISSUE TITLE
Can't see PID coefficients when velocity or position error alert is triggered

### ISSUE THREAD

**Issue by timdrysdale** [dpreid/pidui#4]
Is there a way we can continue to show the PID coefficients and input parameters (but not edit them) after the alert message is triggered (or include append them to the message in alert if space is the issue)? This would save repeating experiments to be sure of the parameters that caused the issue, especially if there is a typo in what you entered compared to what you thought. Alternatively, is there a new optional history widget we could add, which shows the commands that have been issued during your session (and whether velocity or position limits were triggered?)

**Comment by dpreid** [comment]
PID coefficients are now shown when in stopped mode - the mode entered when an alert message shows - but are disabled, so users cannot make changes whilst in stopped mode.
